travis:
  secure:
    BINSTAR_TOKEN: KQlvP8SgTkTbiIzJ/v39MDaQ3UnCuro8gcCiHx/pW5tKcZ+EaLB5ZBPsRWORlLU6Hcfranxm5MNvxQLydwA74OocDHzMDC6B3UjUBTcST6d07PvnzYvtlBWS79TRrXYoNGoN04ZXTshm6fHZdDMnp6JUpEyEe8dRIwriVAiPdAigVc7uukdkwtbhkNAdiSjcukDUTAebyMNIREzUpAarnmJDtLAGNynSQoWsk/W2dX2bR0rvMzvT2x2+Da7QJGKWfnkR5/3oeHd67tWVHCQ0joKSnrfB1nb8J7tpDvqIJRhltuxv7DMj3tZzE/C98QMgZCZ2k5zXP/8EK42NuoHRUb8q+as4g6qiOtqh1ps0tmQaE3puuIProJdBk59GkQriT4d79TwBmDKUDNlqVv1IjQzOCgZXmYkz9KzbNyo55qn25i92UnhSpa/5DYq8f76jMcgtUZpUfeiOOZbI2rzJ73E1uwul8HmEYbWzDgeM4uuQgZK3oGcLrwxWvpt5gYSCBvJqvWhjyJcG0l7kaWCFiPIlWcVdhRs9yCfrTV0K8ci4XFJKHsueiqrvo+wxqhNGiYuaucLMnLxDNRfCfCEsIuY5y5r7xfZYPAg2J8eu74BFhjd3YNljeQXXV9lthQMaET81z6TFWcv91ThPsHv98YanbyhS9tje8x1nRFrsZ3Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
